version: "3.9"
services:
 database:
  image: "postgres:latest"
  ports:
  - "5431:5432"
  environment:
   POSTGRES_USER: wood
   POSTGRES_PASSWORD: 123
   POSTGRES_DB: messanger
  volumes:
   - ./db.sql:/docker-entrypoint-initdb.d/db.sql
 messages:
  build: .
  ports:
  - "5000:5000"
  depends_on:
  - database
 authorization:
  build: ../authorization/
  ports:
  - "5001:5001"
  depends_on:
  - database
