# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_proto_pb2 as server__proto__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InformationRequest = channel.unary_unary(
                '/Greeter/InformationRequest',
                request_serializer=server__proto__pb2.RequestSelfInfo.SerializeToString,
                response_deserializer=server__proto__pb2.ClientInfo.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/Greeter/SendMessage',
                request_serializer=server__proto__pb2.Message.SerializeToString,
                response_deserializer=server__proto__pb2.Response.FromString,
                )
        self.AddFriend = channel.unary_unary(
                '/Greeter/AddFriend',
                request_serializer=server__proto__pb2.FriendRequest.SerializeToString,
                response_deserializer=server__proto__pb2.Response.FromString,
                )
        self.DeleteFriend = channel.unary_unary(
                '/Greeter/DeleteFriend',
                request_serializer=server__proto__pb2.DeleteFriendRequest.SerializeToString,
                response_deserializer=server__proto__pb2.Response.FromString,
                )
        self.CreateRoom = channel.unary_unary(
                '/Greeter/CreateRoom',
                request_serializer=server__proto__pb2.CreateRoomRequest.SerializeToString,
                response_deserializer=server__proto__pb2.Response.FromString,
                )
        self.EnterRoom = channel.unary_stream(
                '/Greeter/EnterRoom',
                request_serializer=server__proto__pb2.EnterRoomRequest.SerializeToString,
                response_deserializer=server__proto__pb2.RoomUpdate.FromString,
                )
        self.EscapeOutRoom = channel.unary_unary(
                '/Greeter/EscapeOutRoom',
                request_serializer=server__proto__pb2.EscapeRoom.SerializeToString,
                response_deserializer=server__proto__pb2.Response.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InformationRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFriend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFriend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnterRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EscapeOutRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InformationRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.InformationRequest,
                    request_deserializer=server__proto__pb2.RequestSelfInfo.FromString,
                    response_serializer=server__proto__pb2.ClientInfo.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=server__proto__pb2.Message.FromString,
                    response_serializer=server__proto__pb2.Response.SerializeToString,
            ),
            'AddFriend': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFriend,
                    request_deserializer=server__proto__pb2.FriendRequest.FromString,
                    response_serializer=server__proto__pb2.Response.SerializeToString,
            ),
            'DeleteFriend': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFriend,
                    request_deserializer=server__proto__pb2.DeleteFriendRequest.FromString,
                    response_serializer=server__proto__pb2.Response.SerializeToString,
            ),
            'CreateRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRoom,
                    request_deserializer=server__proto__pb2.CreateRoomRequest.FromString,
                    response_serializer=server__proto__pb2.Response.SerializeToString,
            ),
            'EnterRoom': grpc.unary_stream_rpc_method_handler(
                    servicer.EnterRoom,
                    request_deserializer=server__proto__pb2.EnterRoomRequest.FromString,
                    response_serializer=server__proto__pb2.RoomUpdate.SerializeToString,
            ),
            'EscapeOutRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.EscapeOutRoom,
                    request_deserializer=server__proto__pb2.EscapeRoom.FromString,
                    response_serializer=server__proto__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InformationRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/InformationRequest',
            server__proto__pb2.RequestSelfInfo.SerializeToString,
            server__proto__pb2.ClientInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/SendMessage',
            server__proto__pb2.Message.SerializeToString,
            server__proto__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFriend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/AddFriend',
            server__proto__pb2.FriendRequest.SerializeToString,
            server__proto__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFriend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/DeleteFriend',
            server__proto__pb2.DeleteFriendRequest.SerializeToString,
            server__proto__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/CreateRoom',
            server__proto__pb2.CreateRoomRequest.SerializeToString,
            server__proto__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnterRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Greeter/EnterRoom',
            server__proto__pb2.EnterRoomRequest.SerializeToString,
            server__proto__pb2.RoomUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EscapeOutRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/EscapeOutRoom',
            server__proto__pb2.EscapeRoom.SerializeToString,
            server__proto__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
