# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server_proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12server_proto.proto\"<\n\nClientInfo\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.CodeResult\x12\x11\n\tjson_info\x18\x02 \x01(\t\"&\n\x0fRequestSelfInfo\x12\x13\n\x0b\x63redentials\x18\x01 \x01(\t\"\'\n\x08Response\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.CodeResult\">\n\nRoomUpdate\x12\x1b\n\x06status\x18\x01 \x01(\x0e\x32\x0b.CodeResult\x12\x13\n\x0bnew_message\x18\x02 \x01(\t\"X\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\troom_name\x18\x02 \x01(\t\x12\x14\n\x0cother_client\x18\x03 \x01(\t\x12\x13\n\x0b\x63redentials\x18\x04 \x01(\t\"4\n\rFriendRequest\x12\x0e\n\x06\x66riend\x18\x01 \x01(\t\x12\x13\n\x0b\x63redentials\x18\x02 \x01(\t\":\n\x13\x44\x65leteFriendRequest\x12\x0e\n\x06\x66riend\x18\x01 \x01(\t\x12\x13\n\x0b\x63redentials\x18\x02 \x01(\t\"6\n\x11\x43reateRoomRequest\x12\x0c\n\x04room\x18\x01 \x01(\t\x12\x13\n\x0b\x63redentials\x18\x02 \x01(\t\"5\n\x10\x45nterRoomRequest\x12\x0c\n\x04room\x18\x01 \x01(\t\x12\x13\n\x0b\x63redentials\x18\x02 \x01(\t\"/\n\nEscapeRoom\x12\x0c\n\x04room\x18\x01 \x01(\t\x12\x13\n\x0b\x63redentials\x18\x02 \x01(\t**\n\nCodeResult\x12\x0b\n\x07unknown\x10\x00\x12\x06\n\x02ok\x10\x01\x12\x07\n\x03\x62\x61\x64\x10\x02\x32\xce\x02\n\x07Greeter\x12\x35\n\x12InformationRequest\x12\x10.RequestSelfInfo\x1a\x0b.ClientInfo\"\x00\x12$\n\x0bSendMessage\x12\x08.Message\x1a\t.Response\"\x00\x12(\n\tAddFriend\x12\x0e.FriendRequest\x1a\t.Response\"\x00\x12\x31\n\x0c\x44\x65leteFriend\x12\x14.DeleteFriendRequest\x1a\t.Response\"\x00\x12-\n\nCreateRoom\x12\x12.CreateRoomRequest\x1a\t.Response\"\x00\x12/\n\tEnterRoom\x12\x11.EnterRoomRequest\x1a\x0b.RoomUpdate\"\x00\x30\x01\x12)\n\rEscapeOutRoom\x12\x0b.EscapeRoom\x1a\t.Response\"\x00\x62\x06proto3')

_CODERESULT = DESCRIPTOR.enum_types_by_name['CodeResult']
CodeResult = enum_type_wrapper.EnumTypeWrapper(_CODERESULT)
unknown = 0
ok = 1
bad = 2


_CLIENTINFO = DESCRIPTOR.message_types_by_name['ClientInfo']
_REQUESTSELFINFO = DESCRIPTOR.message_types_by_name['RequestSelfInfo']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_ROOMUPDATE = DESCRIPTOR.message_types_by_name['RoomUpdate']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_FRIENDREQUEST = DESCRIPTOR.message_types_by_name['FriendRequest']
_DELETEFRIENDREQUEST = DESCRIPTOR.message_types_by_name['DeleteFriendRequest']
_CREATEROOMREQUEST = DESCRIPTOR.message_types_by_name['CreateRoomRequest']
_ENTERROOMREQUEST = DESCRIPTOR.message_types_by_name['EnterRoomRequest']
_ESCAPEROOM = DESCRIPTOR.message_types_by_name['EscapeRoom']
ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'server_proto_pb2'
  # @@protoc_insertion_point(class_scope:ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

RequestSelfInfo = _reflection.GeneratedProtocolMessageType('RequestSelfInfo', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSELFINFO,
  '__module__' : 'server_proto_pb2'
  # @@protoc_insertion_point(class_scope:RequestSelfInfo)
  })
_sym_db.RegisterMessage(RequestSelfInfo)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'server_proto_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

RoomUpdate = _reflection.GeneratedProtocolMessageType('RoomUpdate', (_message.Message,), {
  'DESCRIPTOR' : _ROOMUPDATE,
  '__module__' : 'server_proto_pb2'
  # @@protoc_insertion_point(class_scope:RoomUpdate)
  })
_sym_db.RegisterMessage(RoomUpdate)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'server_proto_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

FriendRequest = _reflection.GeneratedProtocolMessageType('FriendRequest', (_message.Message,), {
  'DESCRIPTOR' : _FRIENDREQUEST,
  '__module__' : 'server_proto_pb2'
  # @@protoc_insertion_point(class_scope:FriendRequest)
  })
_sym_db.RegisterMessage(FriendRequest)

DeleteFriendRequest = _reflection.GeneratedProtocolMessageType('DeleteFriendRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEFRIENDREQUEST,
  '__module__' : 'server_proto_pb2'
  # @@protoc_insertion_point(class_scope:DeleteFriendRequest)
  })
_sym_db.RegisterMessage(DeleteFriendRequest)

CreateRoomRequest = _reflection.GeneratedProtocolMessageType('CreateRoomRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEROOMREQUEST,
  '__module__' : 'server_proto_pb2'
  # @@protoc_insertion_point(class_scope:CreateRoomRequest)
  })
_sym_db.RegisterMessage(CreateRoomRequest)

EnterRoomRequest = _reflection.GeneratedProtocolMessageType('EnterRoomRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENTERROOMREQUEST,
  '__module__' : 'server_proto_pb2'
  # @@protoc_insertion_point(class_scope:EnterRoomRequest)
  })
_sym_db.RegisterMessage(EnterRoomRequest)

EscapeRoom = _reflection.GeneratedProtocolMessageType('EscapeRoom', (_message.Message,), {
  'DESCRIPTOR' : _ESCAPEROOM,
  '__module__' : 'server_proto_pb2'
  # @@protoc_insertion_point(class_scope:EscapeRoom)
  })
_sym_db.RegisterMessage(EscapeRoom)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CODERESULT._serialized_start=593
  _CODERESULT._serialized_end=635
  _CLIENTINFO._serialized_start=22
  _CLIENTINFO._serialized_end=82
  _REQUESTSELFINFO._serialized_start=84
  _REQUESTSELFINFO._serialized_end=122
  _RESPONSE._serialized_start=124
  _RESPONSE._serialized_end=163
  _ROOMUPDATE._serialized_start=165
  _ROOMUPDATE._serialized_end=227
  _MESSAGE._serialized_start=229
  _MESSAGE._serialized_end=317
  _FRIENDREQUEST._serialized_start=319
  _FRIENDREQUEST._serialized_end=371
  _DELETEFRIENDREQUEST._serialized_start=373
  _DELETEFRIENDREQUEST._serialized_end=431
  _CREATEROOMREQUEST._serialized_start=433
  _CREATEROOMREQUEST._serialized_end=487
  _ENTERROOMREQUEST._serialized_start=489
  _ENTERROOMREQUEST._serialized_end=542
  _ESCAPEROOM._serialized_start=544
  _ESCAPEROOM._serialized_end=591
  _GREETER._serialized_start=638
  _GREETER._serialized_end=972
# @@protoc_insertion_point(module_scope)
